export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const CREATE_SCORM_SUCCESS = "CREATE_SCORM_SUCCESS"
export const UPDATE_SCORM_SUCCESS = "UPDATE_SCORM_SUCCESS"

export const GET_EDUCATIONS_SUCCESS = "GET_EDUCATIONS_SUCCESS";